import { configureStore, createSlice } from '@reduxjs/toolkit';

interface IState {
  [title: string]: Array<{
    title: string;
    category: string;
    price: number;
    complete: boolean;
    link: string;
  }>;
}

const initialState: IState = {
  'Звук в зале': [
    {
      title: 'NAD M17 V2i',
      category: 'AV - процессор',
      price: 599990,
      complete: false,
      link: 'https://ci-group.ru/product/nad-m17-v2i-tsifrovoy-predusilitel',
    },
    {
      title: 'NAD M28',
      category: 'Усилитель мощности (7 каналов)',
      price: 449990,
      complete: false,
      link: 'https://ci-group.ru/product/nad-m28-usilitel-moschnosti',
    },
    {
      title: 'NAD M23',
      category: 'Усилитель мощности (2 канала)',
      price: 299990,
      complete: false,
      link: 'https://ci-group.ru/product/nad-m23-usilitel-moschnosti',
    },
    {
      title: 'NAD M23',
      category: 'Усилитель мощности (2 канала)',
      price: 299990,
      complete: false,
      link: 'https://ci-group.ru/product/nad-m23-usilitel-moschnosti',
    },
    {
      title: 'JBL HDI-3800 Grey Oak',
      category: 'Напольная акустика (Фронтальные)',
      price: 439990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/napolnaya-akustika-jbl-hdi-3800-grey-oak',
    },
    {
      title: 'JBL HDI 4500 Grey Oak',
      category: 'Акустика центрального канала',
      price: 160000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akustika-centralnogo-kanala-jbl-hdi-4500-grey-oak',
    },
    {
      title: 'JBL HDI 3600 Grey Oak',
      category: 'Напольная акустика (Боковые)',
      price: 369000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/napolnaya-akustika-jbl-hdi-3600-grey-oak',
    },
    {
      title: 'JBL HDI 1600 Grey Oak',
      category: 'Полочная акустика (Тыловые)',
      price: 149990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/polochnaya-akustika-jbl-hdi-1600-grey-oak',
    },
    {
      title: 'JBL HDI FS Black',
      category: 'Стойки для полочной акустики (2шт, для тыловых)',
      price: 2 * 50000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/stoyka-pod-akustiku-jbl-hdi-fs-black',
    },
    {
      title: 'JBL HDI 1600 Grey Oak',
      category: 'Полочная акустика (Верхние фронтальные)',
      price: 149990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/polochnaya-akustika-jbl-hdi-1600-grey-oak',
    },
    {
      title: 'JBL HDI 1600 Grey Oak',
      category: 'Полочная акустика (Верхние тыловые)',
      price: 149990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/polochnaya-akustika-jbl-hdi-1600-grey-oak',
    },
    {
      title: 'JBL HDI 1200P Grey Oak',
      category: 'Сабвуфер',
      price: 225000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/sabvufer-jbl-hdi-1200p-grey-oak',
    },
    {
      title: 'PowerGrip YG-3',
      category: 'Сетевой фильтр',
      price: 189900,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/filtr-setevoy-powergrip-yg-3',
    },
    {
      title: 'Wire World Stratus 7 Power Cord 1.0m',
      category: 'Кабель питания (1 метр, для M17)',
      price: 12730,
      complete: true,
      link: 'https://kaliningrad.pult.ru/product/kabel-pitaniya-wire-world-stratus-7-10m-stp10meu7',
    },
    {
      title: 'Wire World Stratus 7 Power Cord 1.0m',
      category: 'Кабель питания (1 метр, для M28)',
      price: 12730,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-pitaniya-wire-world-stratus-7-10m-stp10meu7',
    },
    {
      title: 'Wire World Stratus 7 Power Cord 1.0m',
      category: 'Кабель питания (1 метр, для M23)',
      price: 12730,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-pitaniya-wire-world-stratus-7-10m-stp10meu7',
    },
    {
      title: 'Wire World Stratus 7 Power Cord 1.0m',
      category: 'Кабель питания (1 метр, для M23)',
      price: 12730,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-pitaniya-wire-world-stratus-7-10m-stp10meu7',
    },
    {
      title: 'Wire World Stratus 7 Power Cord 2.0m',
      category: 'Кабель питания (2 метр, для сабвуфера)',
      price: 17400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-setevoy-wire-world-stratus-7-20m',
    },
    {
      title: 'Wire World Oasis 8 Interconnect 0.5m',
      category: 'Межблочный аудио кабель (7 шт по 0.5 метраа, для M28)',
      price: 4 * 14100,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-mejblochnyy-audio-wire-world-oasis-8-interconnect-0-5m-pair--oai0-5m-8',
    },
    {
      title: 'Wire World Oasis 8 Interconnect 0.5m',
      category: 'Межблочный аудио кабель (2 шт по 0.5 метра, для M23)',
      price: 2 * 14100,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-mejblochnyy-audio-wire-world-oasis-8-interconnect-0-5m-pair--oai0-5m-8',
    },
    {
      title: 'Wire World Oasis 8 Interconnect 0.5m',
      category: 'Межблочный аудио кабель (2 шт по 0.5 метра, для M23)',
      price: 2 * 14100,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-mejblochnyy-audio-wire-world-oasis-8-interconnect-0-5m-pair--oai0-5m-8',
    },
    {
      title: 'Wire World Oasis 8 Subwoofer Interconnect',
      category: 'Сабвуферный аудио кабель (3 метра)',
      price: 13700,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-mejblochnyy-audio-wire-world-oasis-8-subwoofer-interconnect-3-0m--osw3-0m-8',
    },
    {
      title: 'Wire World Sphere HDMI 2.1 Cable 3.0m',
      category: 'HDMI кабель (3 метра, для Яндекс Станции Макс)',
      price: 8170,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/hdmi-kabel-wire-world-sph3-0m-48-sphere-hdmi-2-1-cable-3m',
    },
    {
      title: 'Wire World Sphere HDMI 2.1 Cable 1.0m',
      category: 'HDMI кабель (1 метра, для телевизора)',
      price: 6700,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/hdmi-kabel-wire-world-sph1-0m-48-sphere-hdmi-2-1-cable-1m',
    },
    {
      title: 'Wire World Sphere HDMI 2.1 Cable 1.0m',
      category: 'HDMI кабель (1 метр, для модуля с Яндекс ТВ)',
      price: 6700,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/hdmi-kabel-wire-world-sph1-0m-48-sphere-hdmi-2-1-cable-1m',
    },
    {
      title: 'Wire World Pulse 3.5mm to 2 RCA 2.0m',
      category: 'Аудио кабель Jack 3.5 - 2 RCA (2 метра, для Яндекс Станции Макс)',
      price: 5130,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-mejblochnyy-audio-wire-world-pulse-3-5mm-to-2-rca-2-0m',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (2 x 2.5 метров, на фронтальные)',
      price: 2 * 3960 * 2.5,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (1 метр, на центральный)',
      price: 3960,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (2 x 7.5 метров, на боковые)',
      price: 2 * 3960 * 7.5,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (2 x 15 метров, на тыловые)',
      price: 2 * 3960 * 15,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (2 x 5 метров, на верхние фронтальные)',
      price: 2 * 3960 * 5,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (2 x 17.5 метров, на верхные тыловые)',
      price: 2 * 3960 * 17.5,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Uni-Term Silver Spades',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/wire-world-set-of-8-uni-term-silver-spades-w-sockets',
    },
    {
      title: 'Wire World Uni-Term Silver Spades',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/wire-world-set-of-8-uni-term-silver-spades-w-sockets',
    },
    {
      title: 'Wire World Uni-Term Silver Spades',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/wire-world-set-of-8-uni-term-silver-spades-w-sockets',
    },
    {
      title: 'Wire World Uni-Term Silver Bananas',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/razem-wire-world-set-of-8-uni-term-silver-bananas-w-sockets',
    },
    {
      title: 'Wire World Uni-Term Silver Bananas',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/razem-wire-world-set-of-8-uni-term-silver-bananas-w-sockets',
    },
    {
      title: 'Wire World Uni-Term Silver Bananas',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/razem-wire-world-set-of-8-uni-term-silver-bananas-w-sockets',
    },
    {
      title: 'NorStone Stabbl HiFi black',
      category: 'Подставка под аппаратуру',
      price: 49990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/norstone-stabbl-hifi-black',
    },
    {
      title: 'Wire World JUMPOAS Oasis Biwiring Jumpers (Set of 4)',
      category: 'Перемычки Spade - Banana (на фронтальные)',
      price: 12000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/peremychki-wire-world-jumpoas-oasis-biwiring-jumpers--set-of-4---spade-to-banana',
    },
    {
      title: 'Wire World JUMPOAS Oasis Biwiring Jumpers (Set of 4)',
      category: 'Перемычки Spade - Banana (на боковые)',
      price: 12000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/peremychki-wire-world-jumpoas-oasis-biwiring-jumpers--set-of-4---spade-to-banana',
    },
    {
      title: 'Wire World JUMPOAS Oasis Biwiring Jumpers (Set of 4)',
      category: 'Перемычки Spade - Banana (на тыловые)',
      price: 12000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/peremychki-wire-world-jumpoas-oasis-biwiring-jumpers--set-of-4---spade-to-banana',
    },
    {
      title: 'Wire World JUMPOAS Oasis Biwiring Jumpers (Set of 4)',
      category: 'Перемычки Spade - Banana (на верхние фронтальные)',
      price: 12000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/peremychki-wire-world-jumpoas-oasis-biwiring-jumpers--set-of-4---spade-to-banana',
    },
    {
      title: 'Wire World JUMPOAS Oasis Biwiring Jumpers (Set of 4)',
      category: 'Перемычки Spade - Banana (на верхние тыловые)',
      price: 12000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/peremychki-wire-world-jumpoas-oasis-biwiring-jumpers--set-of-4---spade-to-banana',
    },
    {
      title: 'Wire World JUMPOAS Oasis Biwiring Jumpers (Set of 4)',
      category: 'Перемычки Spade - Banana (на центральный)',
      price: 12000,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/peremychki-wire-world-jumpoas-oasis-biwiring-jumpers--set-of-4---spade-to-banana',
    },
  ],

  'Звук в кабинете': [
    {
      title: 'NAD M33',
      category: 'Интегральный усилитель',
      price: 449990,
      complete: false,
      link: 'https://ci-group.ru/product/nad-m33-integralnyy-usilitel',
    },
    {
      title: 'JBL HDI-3800 Grey Oak',
      category: 'Напольная акустика',
      price: 439990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/napolnaya-akustika-jbl-hdi-3800-grey-oak',
    },
    {
      title: 'PowerGrip YG-3',
      category: 'Сетевой фильтр',
      price: 189900,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/filtr-setevoy-powergrip-yg-3',
    },
    {
      title: 'Wire World Stratus 7 Power Cord 1.0m',
      category: 'Кабель питания (1 метр)',
      price: 12730,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-pitaniya-wire-world-stratus-7-10m-stp10meu7',
    },
    {
      title: 'Wire World Pulse 3.5mm to 2 RCA 2.0m',
      category: 'Аудио кабель Jack 3.5 - 2 RCA (2 метра, для Яндекс Станции Мини)',
      price: 5130,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/kabel-mejblochnyy-audio-wire-world-pulse-3-5mm-to-2-rca-2-0m',
    },
    {
      title: 'Wire World Oasis 8 Speaker Cable',
      category: 'Акустический кабель в нарезку (2 x 2.5 метров)',
      price: 2 * 3960 * 2.5,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/akusticheskiy-kabel-wire-world-oasis-8-speaker-cable-50m-spool--oasm050-8',
    },
    {
      title: 'Wire World Uni-Term Silver Spades',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/wire-world-set-of-8-uni-term-silver-spades-w-sockets',
    },
    {
      title: 'Wire World Uni-Term Silver Bananas',
      category: 'Разъём для акустического кабеля (Комплект из 8 штук)',
      price: 10400,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/razem-wire-world-set-of-8-uni-term-silver-bananas-w-sockets',
    },
    {
      title: 'NorStone Stabbl HiFi black',
      category: 'Подставка под аппаратуру',
      price: 49990,
      complete: false,
      link: 'https://kaliningrad.pult.ru/product/norstone-stabbl-hifi-black',
    },
  ],
};

const slice = createSlice({
  name: 'dream-music',
  initialState,
  reducers: {},
});

export const actions = slice.actions;
export const store = configureStore({ reducer: slice.reducer });
export type RootState = ReturnType<typeof store.getState>;
